[pytest]
markers =
    unit: fast isolated tests
    integration: tests with services (network/local)
    e2e: full system tests

filterwarnings =
    ignore:numpy\.core\._multiarray_umath is deprecated.*:DeprecationWarning
